### ISSUE TITLE
$dcc.sessionlist crashes kvirc

### ISSUE THREAD

**Issue by pragmaware** [kvirc/kvirc-issue-test#37]
**Reported by ruuk on 26 Oct 2007 10:51 UTC**
crashes on $dcc.sessionList type /echo $dcc.sessionlist and see for 
yourself :)

**Comment by pragmaware** [comment]
**Modified by anonymous on 26 Oct 2007 10:51 UTC**

**Comment by pragmaware** [comment]
**Comment by mren on 28 Feb 2008 02:31 UTC**
Still crashes in r1171, here the backtrace:

(no debugging symbols found)[host libthread_db library "/lib/libthread_db.so.1".[[BR]([BR]]
Using)]
(no debugging symbols found)[handler]([BR]]
(...)[[BR]]
[KCrash)[ 0xb5741c0e in ?? () from /usr/share/kvirc/3.2/modules/libkvidcc.so[[BR]([BR]]
#6)]
#7  0x081e3a1f in KviKvsTreeNodeModuleFunctionCall::evaluateReadOnly ()[ 0x081dc38f in KviKvsTreeNodeDataList::evaluate ()[[BR]([BR]]
#8)]
#9  0x081dba93 in KviKvsTreeNodeCoreSimpleCommand::execute ()[0x081cff46 in KviKvsScript::executeInternal ()[[BR]([BR]]
#10)]
#11 0x081d0018 in KviKvsScript::execute ()[0x0816862c in KviUserInput::parseCommand ()[[BR]([BR]]
#12)]
#13 0x08168ee2 in KviUserInput::parse ()[0x0825a97e in KviInput::inputEditorEnterPressed ()[[BR]([BR]]
#14)]
#15 0x0825ac5e in KviInput::qt_invoke ()[0xb6f376b9 in QObject::activate_signal () from /usr/qt/3/lib/libqt-mt.so.3[[BR]([Br]]
#16)]
#17 0xb6f3830d in QObject::activate_signal () from /usr/qt/3/lib/libqt-mt.so.3[0x08257bfe in KviInputEditor::enterPressed ()[[BR]([BR]]
#18)]
#19 0x08260a59 in KviInputEditor::keyPressEvent ()[0xb6f70560 in QWidget::event () from /usr/qt/3/lib/libqt-mt.so.3[[BR]([BR]]
#20)]
#21 0xb6ed8747 in QApplication::internalNotify () from /usr/qt/3/lib/libqt-mt.so.3[0xb6ed9a46 in QApplication::notify () from /usr/qt/3/lib/libqt-mt.so.3[[BR]([BR]]
#22)]
#23 0xb76864fe in KApplication::notify () from /usr/kde/3.5/lib/libkdecore.so.4[0xb6e76d48 in QETWidget::translateKeyEvent () from /usr/qt/3/lib/libqt-mt.so.3[[BR]([BR]]
#24)]
#25 0xb6e788e9 in QApplication::x11ProcessEvent () from /usr/qt/3/lib/libqt-mt.so.3[0xb6e8883a in QEventLoop::processEvents () from /usr/qt/3/lib/libqt-mt.so.3[[BR]([BR]]
#26)]
#27 0xb6eeee30 in QEventLoop::enterLoop () from /usr/qt/3/lib/libqt-mt.so.3[0xb6eeecb6 in QEventLoop::exec () from /usr/qt/3/lib/libqt-mt.so.3[[BR]([BR]]
#28)]
#29 0xb6ed81df in QApplication::exec () from /usr/qt/3/lib/libqt-mt.so.3[0x0813dd07 in main ()[[BR]([BR]]
#30)]

**Comment by pragmaware** [comment]
**Modified by anonymous on 5 Mar 2008 18:33 UTC**

**Comment by pragmaware** [comment]
**Comment by Pragma on 13 Mar 2008 02:23 UTC**
Fixed on the current svn
