### ISSUE TITLE
Kvirc SVN rev1077 on qt3 crashes randomly

### ISSUE THREAD

**Issue by pragmaware** [kvirc/kvirc-issue-test#65]
**Reported by BehnamFedora   incruster on 12 Jan 2008 20:51 UTC**
I'm using Kvirc SVN rev1077 with qt3 on Fedora8 ( the latest SVN revision at this moment Saturday 12 January 2008)

It crashes randomly.

Here, you can see a trace done with gdb -x kvirc.gdb --args kvirc > out.txt
In kvirc.gdb, there is 

" define hookpost-run

bt

end

run

quit "

that I've been given by " thexception " on #kvirc ,freenode

Here are three files 
The first is when I first used gdb to collect informations
The second one, I have been told that there was a link with the notifier windows, so I force disabled it
The third one, even after disabling the notifier window, still the same error

Notice that the first one doesn't seem to have link with the two last ones.

**Comment by pragmaware** [comment]
**Comment by mren on 12 Jan 2008 23:49 UTC**
I can confirm this bug on gentoo, also r1077.
Here's the backlog from KDE-crashmanager:

(no debugging symbols found)[host libthread_db library "/lib/libthread_db.so.1".[[BR]([BR]]
Using)]
(no debugging symbols found)[debugging symbols found)[[BR]([BR]]
[...][[BR]]
(no)]
[handler](KCrash)[ 0x0813a1d5 in KviIsOnNotifyListManager::handleUserhost ()[[BR]([BR]]
#6)]
#7  0x081f089e in KviServerParser::parseNumericUserhost ()[ 0x081d1b82 in KviServerParser::parseMessage ()[[BR]([BR]]
#8)]
#9  0x0811bb9a in KviIrcConnection::incomingMessage ()[0x0812a369 in KviIrcLink::processData ()[[BR]([BR]]
#10)]
#11 0x0812cb89 in KviIrcSocket::readData ()[0x082937bd in KviIrcSocket::qt_invoke ()[[BR]([BR]]
#12)]
#13 0xb6f1f6b9 in QObject::activate_signal () from /usr/qt/3/lib/libqt-mt.so.3[0xb6f20212 in QObject::activate_signal () from /usr/qt/3/lib/libqt-mt.so.3[[BR]([BR]]
#14)]
#15 0xb7253880 in QSocketNotifier::activated () from /usr/qt/3/lib/libqt-mt.so.3[0xb6f3d24f in QSocketNotifier::event () from /usr/qt/3/lib/libqt-mt.so.3[[BR]([BR]]
#16)]
#17 0xb6ec0747 in QApplication::internalNotify () from /usr/qt/3/lib/libqt-mt.so.3[0xb6ec12c1 in QApplication::notify () from /usr/qt/3/lib/libqt-mt.so.3[[BR]([BR]]
#18)]
#19 0xb765f91e in KApplication::notify () from /usr/kde/3.5/lib/libkdecore.so.4[0xb6eb53a1 in QEventLoop::activateSocketNotifiers () from /usr/qt/3/lib/libqt-mt.so.3[[BR]([BR]]
#20)]
#21 0xb6e708d4 in QEventLoop::processEvents () from /usr/qt/3/lib/libqt-mt.so.3[0xb6ed6e30 in QEventLoop::enterLoop () from /usr/qt/3/lib/libqt-mt.so.3[[BR]([BR]]
#22)]
#23 0xb6ed6cb6 in QEventLoop::exec () from /usr/qt/3/lib/libqt-mt.so.3[0xb6ec01df in QApplication::exec () from /usr/qt/3/lib/libqt-mt.so.3[[BR]([BR]]
#24)]
#25 0x08131877 in main ()[[BR]]

**Comment by pragmaware** [comment]
**Comment by Behnam < incruster@hotmail.com > on 13 Jan 2008 19:20 UTC**
I've added this tracelog " out4.txt" which refers to notifier again ...

**Comment by pragmaware** [comment]
**Comment by Behnam < incruster@hotmail.com > on 14 Jan 2008 11:11 UTC**
I added another one, this time, it seems that the notifier window involving is confirmed ...

**Comment by pragmaware** [comment]
**Comment by Behnam <incruster@hotmail.com> on 14 Jan 2008 17:22 UTC**
More and more and more ...

Now I can be sure it's something to do with the Notifier Windows
I've noticed it often occurs when someone highlights me, but not everytime

**Comment by pragmaware** [comment]
**Comment by Behnam <incruster@hotmail.com> on 16 Jan 2008 05:10 UTC**
Still the same problem on r1090

**Comment by pragmaware** [comment]
**Comment by Behnam < incruster@hotmail.com > on 16 Jan 2008 13:41 UTC**
I'm on r1058 and it works very well, but when I get on 1091, it crashes everytime

**Comment by pragmaware** [comment]
**Comment by mren on 5 Feb 2008 22:25 UTC**
Ticket #72 is a duplicate of this and has another backtrace

**Comment by pragmaware** [comment]
**Comment by mren on 25 Feb 2008 13:56 UTC**
Should be fixed now (r1148)
